- Add auth v1 support - Add more scenarios

diff --git a/bin/wrapper b/bin/wrapper
--- a/bin/wrapper
+++ b/bin/wrapper
@@ -21,7 +21,7 @@
 usage() {
     cat << EOF
 
-Usage `basename $0` -m <mode> [-i <master_ip>] [-c <concurrency> ] [-o <operations>]
+Usage `basename $0` -m <mode> [-i <master_ip>] [-c <concurrency> ] [-o <operations>] [-f <inc>]
     mode can be one of those:
      - install : deploy the ssbench virtualenv
      - spawn_workers : start as much workers as CPU
@@ -29,6 +29,7 @@ Usage `basename $0` -m <mode> [-i <master_ip>] [-c <concurrency> ] [-o <operatio
      - kill_workers : stop all current workers on local host
      - rampup : start the rampup evaluation
        (use -o option to specify the amount of operation to perform)
+       (use -f option to specify client concurrency to add for next run)
      - bench : start the bench evaluation
        (use -c option to specify client concurrency
 Some of environnement variables must be set:
@@ -37,12 +38,16 @@ Some of environnement variables must be set:
        been checkouted)
      - CHECKOUTDIR : the project directory 
     for bench and rampup modes :
-     - KEYSTONE_ENDPOINT : the authentication keystone endpoint
+     - KEYSTONE_ENDPOINT : the authentication keystone endpoint or
+                           swift authentication for auth v1.0
      - TENANT : the user tenant
-     - USERNAME : the username
+     - TUSER : the username
      - PASSWORD : the user password
+     - AUTH : specify V1 or let it empty for keystone auth
     for bench mode :
      - SCENARIOS : a comma sperated list of scenarios name
+    for rampup mode :
+     - SCENARIOS : scenario to use for the rampup mode
 EOF
     exit 1
 }
@@ -58,7 +63,9 @@ EOF
     usage
 }
 
-[ -z "$WORKCONC" ] && WORKCONC=16
+#[ -z "$WORKCONC" ] && WORKCONC=16
+[ -z "$WORKCONC" ] && WORKCONC=256
+[ -z "$AUTH" ] && AUTH="V2"
 
 TAG="0.2.13"
 RAMPUPCSVDIR=/tmp/csvrampup
@@ -83,7 +90,7 @@ check_env_vars() {
     # Verify some mandatory environement variables
     [ -z "$KEYSTONE_ENDPOINT" ] && { echo "KEYSTONE_ENDPOINT is not set"; usage; }
     [ -z "$TENANT" ] && { echo "TENANT is not set"; usage; }
-    [ -z "$USERNAME" ] && { echo "USERNAME is not set"; usage; }
+    [ -z "$TUSER" ] && { echo "TUSER is not set"; usage; }
     [ -z "$PASSWORD" ] && { echo "PASSSWORD is not set"; usage; }
 }
 
@@ -130,21 +137,21 @@ install_ssbench() {
     deactivate
 }
 
-get_extract_token() {
-    echo "Working in $TDIR"
-    curl -s -d "{\"auth\": {\"tenantName\": \"$TENANT\", \"passwordCredentials\": \
-        {\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}}}" \
-        -H 'Content-type: application/json' $KEYSTONE_ENDPOINT/tokens > $TDIR/token
-    python -c "import json;import sys; t=json.load(file(sys.argv[1])); \
-        print t['access']['token']['id']" $TDIR/token > $TDIR/tokenid
-    python -c "import json;import sys; import pprint; t=json.load(file(sys.argv[1])); \
-        e=[e for e in t['access']['serviceCatalog'] if e['name'] == 'swift']; \
-        print e[0]['endpoints'][0]['publicURL']" $TDIR/token > $TDIR/swift_endpoint
-    # ssbench fails to resolv hostname (strange behaviour) so manually set ip of cw-vip-swift
-    #sed -i 's/cw-vip-swift.enovance.com/10.68.0.152/' $TDIR/swift_endpoint
-    [ "`wc -l $TDIR/tokenid | cut -d' ' -f1`" = 1 ] && \
-    [ "`wc -l $TDIR/swift_endpoint | cut -d' ' -f1`" = 1 ]
-}
+#get_extract_token() {
+#    echo "Working in $TDIR"
+#    curl -s -d "{\"auth\": {\"tenantName\": \"$TENANT\", \"passwordCredentials\": \
+#        {\"username\": \"$USERNAME\", \"password\": \"$PASSWORD\"}}}" \
+#        -H 'Content-type: application/json' $KEYSTONE_ENDPOINT/tokens > $TDIR/token
+#    python -c "import json;import sys; t=json.load(file(sys.argv[1])); \
+#        print t['access']['token']['id']" $TDIR/token > $TDIR/tokenid
+#    python -c "import json;import sys; import pprint; t=json.load(file(sys.argv[1])); \
+#        e=[e for e in t['access']['serviceCatalog'] if e['name'] == 'swift']; \
+#        print e[0]['endpoints'][0]['publicURL']" $TDIR/token > $TDIR/swift_endpoint
+#    # ssbench fails to resolv hostname (strange behaviour) so manually set ip of cw-vip-swift
+#    #sed -i 's/cw-vip-swift.enovance.com/10.68.0.152/' $TDIR/swift_endpoint
+#    [ "`wc -l $TDIR/tokenid | cut -d' ' -f1`" = 1 ] && \
+#    [ "`wc -l $TDIR/swift_endpoint | cut -d' ' -f1`" = 1 ]
+#}
 
 kill_workers() {
     echo "Kill all workers"
@@ -179,7 +186,7 @@ spawn_workers() {
 clean_swift() {
     cd $SSDESTDIR
     . bin/activate
-    swift --os-username=$USERNAME --os-tenant-name=$TENANT \
+    swift --os-username=$TUSER --os-tenant-name=$TENANT \
           --os-password=$PASSWORD --os-auth-url=$KEYSTONE_ENDPOINT delete --all
     cd - > /dev/null
     deactivate
@@ -195,10 +202,22 @@ start_bench() {
         }
         cd $SSDESTDIR
         . bin/activate
-        bin/ssbench-master run-scenario -S `cat $TDIR/swift_endpoint` \
-            -T `cat $TDIR/tokenid` \
-            -f $spath \
-            -u $concurrency -s $TDIR/${name}.stat
+#        bin/ssbench-master run-scenario -S `cat $TDIR/swift_endpoint` \
+#            -T `cat $TDIR/tokenid` \
+#            -f $spath \
+#            -u $concurrency -s $TDIR/${name}.stat
+        [ "$AUTH" = "V1" ] && {
+            bin/ssbench-master run-scenario --os-tenant-name=$TENANT \
+                -U $TENANT:$TUSER -K $PASSWORD -A $KEYSTONE_ENDPOINT \
+                -f $spath -o $op_count \
+                -u $concurrency -s $TDIR/${name}.stat
+        } || {
+            bin/ssbench-master run-scenario --os-tenant-name=$TENANT \
+                --os-username=$TUSER --os-password=$PASSWORD \
+                --os-auth-url=$KEYSTONE_ENDPOINT \ 
+                -f $spath \
+                -u $concurrency -s $TDIR/${name}.stat
+        }
         bin/ssbench-master report-scenario -s $TDIR/${name}.stat.gz \
             -f $TDIR/${name}.report
         cd - > /dev/null
@@ -213,7 +232,7 @@ start_rampup() {
     # Start values
     concurrency=0
     stage=0
-    concurrency_inc=2
+    concurrency_inc=$inc_count
     limit="notfound"
     csvfile="$RAMPUPCSVDIR/`date +%s`.csv"
     declare -a ops
@@ -223,16 +242,36 @@ start_rampup() {
         stage=$((stage + 1))
         concurrency=$((concurrency + concurrency_inc))
         echo "Start stage with concurrency=$concurrency"
-        spath=$WORKSPACE/$CHECKOUTDIR/scenarios/rampup.scenario
+        [ -n "$SCENARIOS" ] && {
+            # Only one scenario can be use for rampup mode
+            name=`echo $SCENARIOS | cut -d, -f1`
+            spath=$WORKSPACE/$CHECKOUTDIR/scenarios/${name}.scenario
+        } || {
+            spath=$WORKSPACE/$CHECKOUTDIR/scenarios/rampup.scenario
+        }
         cd $SSDESTDIR
         . bin/activate
-        token=`cat $TDIR/tokenid`
-        endpoint=`cat $TDIR/swift_endpoint`
-        bin/ssbench-master run-scenario -q -S $endpoint \
-            -T $token \
-            -f $spath \
-            -o $op_count \
-            -u $concurrency -s $TDIR/rampup.stat
+#        token=`cat $TDIR/tokenid`
+#        endpoint=`cat $TDIR/swift_endpoint`
+#        bin/ssbench-master run-scenario -q -S $endpoint \
+#            -T $token \
+#            -f $spath \
+#            -o $op_count \
+#            -u $concurrency -s $TDIR/rampup.stat
+        [ "$AUTH" = "V1" ] && {
+            bin/ssbench-master run-scenario --os-tenant-name=$TENANT \
+                -U $TENANT:$TUSER -K $PASSWORD -A $KEYSTONE_ENDPOINT \
+                -f $spath \
+                -o $op_count \
+                -u $concurrency -s $TDIR/rampup.stat
+        } || {
+            bin/ssbench-master run-scenario --os-tenant-name=$TENANT \
+                --os-username=$TUSER --os-password=$PASSWORD \
+                --os-auth-url=$KEYSTONE_ENDPOINT \ 
+                -f $spath \
+                -o $op_count \
+                -u $concurrency -s $TDIR/rampup.stat
+        }
         cd - > /dev/null
         rm -f /tmp/rampup
         ssbench-master report-scenario -s $TDIR/rampup.stat.gz \
@@ -253,10 +292,14 @@ start_rampup() {
             echo "Result details can be found in $csvfile"
             limit="found"
         }
+        [ "$limit" = "notfound" ] && {
+            echo "stand a while (60s) ..."
+            sleep 60
+        }
     done
 }
 
-while getopts “hm:i:c:o:” OPTION; do
+while getopts “hm:i:c:o:f:” OPTION; do
     case $OPTION in
         h)
         usage
@@ -273,6 +316,9 @@ while getopts “hm:i:c:o:” OPTION; do
         ;;
         o)
         op=$OPTARG
+        ;;
+        f)
+        inc=$OPTARG
         ;;
         ?)
         usage
@@ -291,19 +337,22 @@ done
         usage
     }
     concurrency=$conc
-    #[ -n "$op" ] && op_count=$op || op_count=1000
+    [ -n "$op" ] && op_count=$op || op_count=15000
     check_env_vars
     check_env
-    get_extract_token && start_bench $concurrency && parse_created_csv
+#    get_extract_token && start_bench $concurrency && parse_created_csv
+    start_bench $concurrency && parse_created_csv
 }
 
 [ "$mode" = "rampup" ] && {
     [ ! -d $TDIR ] && mkdir -p $TDIR
     [ ! -d $RAMPUPCSVDIR ] && mkdir -p $RAMPUPCSVDIR
-    [ -n "$op" ] && op_count=$op || op_count=1000
+    [ -n "$op" ] && op_count=$op || op_count=15000
+    [ -n "$inc" ] && inc_count=$inc || inc_count=3
     check_env_vars
     check_env
-    get_extract_token && start_rampup
+#    get_extract_token && start_rampup
+    start_rampup
 }
 
 [ "$mode" == "spawn_workers" ] && {
